version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          echo "hello world"
          pip install docker-compose
          docker network create localstack-tutorial
          docker-compose up -d --build
          sudo apt install golang-go
          bash zip-it.sh
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform
          terraform init
          terraform plan
          terraform apply --auto-approve
          awslocal lambda list-functions
          awslocal dynamodb list-tables
          awslocal kinesis list-streams