version: 2.1
jobs:
  build:
    docker:
      - image: localstack/localstack:latest
    steps:
      - checkout # check out the code in the project directory
      # - setup_remote_docker:
      #     version: 19.03.13

      - run: |
          sudo apt update
          sudo apt install awscli
          pip install awsebcli --upgrade --user 
          alias awslocal="aws --endpoint-url=http://localhost:4566 --region ap-southeast-2"
          aws configure set aws_access_key_id fake_id
          aws configure set aws_secret_access_key fake_access_key
          aws configure set default_region ap-southeast-2
          sudo apt-get install unzip
          wget https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
          unzip terraform_1.0.9_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
          echo "hello world"
          # pip install docker-compose
          # docker network create localstack-tutorial
          # docker-compose up -d --build
          # curl -LO https://get.golang.org/$(uname)/go_installer && chmod +x go_installer && ./go_installer && rm go_installer
          # ./zip-it.sh
          terraform init
          # terraform plan
          echo "waiting for S3.."
          until $(nc -zv localhost 4566); do
              printf '.'
              sleep 1
          done
          terraform apply --auto-approve
          awslocal lambda list-functions
          awslocal dynamodb list-tables
          awslocal kinesis list-streams